### ISSUE TITLE
TypeError: undefined is not an object (evaluating '$element.context.getAttribute') 

### ISSUE THREAD

**Issue by jbeuckm** [nglar/ngTouchstart#1]
I get this when I tap on the element with the ng-touchstart directive:

TypeError: undefined is not an object (evaluating '$element.context.getAttribute')
onTouchStartngTouchstart.js:9

**Comment by marktopper** [comment]
I will fix this today and update this issue.

**Comment by marktopper** [comment]
Please report back if you still get any errors.

Best regards, Mark.
